modLoader="javafml"
loaderVersion="[44,)"
issueTrackerURL="https://github.com/wagyourtail/anticlientcrasher/issues"
license = "MIT"

[[mods]]
modId = "anticlientcrasher"
version = "${version}"
displayName = "Anti ClientCrasher"
authors = "Wagyourtail"
description = '''
Cancel the effects of the ClientCrasher plugin
'''

[[dependencies.anticlientcrasher]]
modId="minecraft"
mandatory=true
versionRange="[1.19.3]"
ordering="NONE"
side="CLIENT"
